channels:
  - conda-forge
dependencies:
  # -------- Core Python --------
  - python=3.13

  # -------- Build toolchain --------
  - setuptools
  - python-build

  # -------- Libraries --------
  - hdf5
  - hdf4

  # -------- Python Runtime --------
  - numpy                 # package dependency
  - h5py                  # psi-io dependency
  - pyhdf                 # optional hdf4 support
  - scipy                 # optional dependency

  # -------- Testing / QA --------
  - pytest
  - pytest-cov
  - mypy
  - ruff
  - coverage
  - nox

  # -------- Docs --------
  - sphinx
  - sphinx-book-theme
  - sphinx-gallery
  - sphinx-copybutton
  - matplotlib
  - pooch

  # -------- Scripts --------
  - packaging

  # -------- Publish --------
  - twine

  # -------- Pip installs --------
  - pip
  - pip:
      - pthree    # Documentation building

